project:
  type: website

website:
  title: "Ethan Littlestone"
  site-url: https://elittlestone.github.io
  navbar:
    left:
      - text: Home
        href: /
      - text: Single Cell RNA-seq
        href: sc_rna_seq_analysis/index.html
  page-footer: "© 2025 Ethan Littlestone"

format:
  html:
    theme: cosmo
    css: custom_theme.css

